### ISSUE TITLE
'i..java' missing at import

### ISSUE THREAD

**Issue by ZsBT** [broo2s/ingress-apk-mod#1]
after baksmali, import stops with the following: No such file or directory: '/usr/local/ingress/rmod/ingress-apk-mod/trunk/app/smali/com/nianticproject/ingress/common/v/i..java'

Traceback (most recent call last):
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/analyze.py", line 272, in <module>
    Analyzer().analyze(len(sys.argv) > 1 and sys.argv[1] == 'release')
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/analyze.py", line 22, in analyze
    self.auto_analyze()
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/analyze.py", line 86, in auto_analyze
    found, unknown_pkg = self.auto_identify_class(cls, max_unknown_pkg)
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/analyze.py", line 123, in auto_identify_class
    ret = find_class(q)
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/analyze.py", line 114, in find_class
    ret = set(getattr(self, 'find_class_' + q[0])(*([cls, (obf_pkg, unknown)] + q[3:])))
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/analyze.py", line 202, in find_class_super_of
    return [self.obj.edit_cls(obj_name[1:]).get_super()]
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/common.py", line 64, in edit_cls
    return ClassEditor(self, cls)
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/common.py", line 367, in **init**
    self.open()
  File "/usr/local/ingress/rmod/ingress-apk-mod/trunk/bin/common.py", line 370, in open
    self.parts = [open('%s/app/smali/%s' % (HOME, self.cls.get_obf_file_name())).read()]

 Traceback (most recent call last):
  File "bin/import_apk.py", line 29, in <module>
    main(sys.argv[1])
  File "bin/import_apk.py", line 25, in main
    ''' % (LINE_PREFIX, apk,apk), shell=True, executable='/bin/bash')
  File "/usr/lib/python3.2/subprocess.py", line 488, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        rm -rf $MOD_HOME/app
        java -jar $MOD_HOME/lib/apktool.jar d -d -o $MOD_HOME/app --debug-line-prefix ';// ' "/tmp/ingress.apk"
        apktool d /tmp/ingress.apk $MOD_HOME/app
        mkdir -p $MOD_HOME/app  # to not mess up everything if apktool fail
        cp $MOD_HOME/res/app.gitignore $MOD_HOME/app/.gitignore

```
    pushd $MOD_HOME/app
    git init
    git add -f .
    git commit -m "Import."
    git gc
    popd

    $MOD_HOME/bin/analyze.py
' returned non-zero exit status 1
```

yes, i included an 'apktool' command in import py as the java -jar line did not work for me.

**Comment by ZsBT** [comment]
I'm continuing anyway, but stuck at next one:

Traceback (most recent call last):
  File "prepare_lowres.py", line 119, in <module>
    main()
  File "prepare_lowres.py", line 29, in main
    resize('hvga', .6, (24, 30, 36))
  File "prepare_lowres.py", line 64, in resize
    im.resize((round(im.size[0] \* scale), round(im.size[1] \* scale)), Image.ANTIALIAS).save(
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1298, in resize
    im = self.im.stretch(size, resample)
TypeError: integer argument expected, got float

**Comment by broo2s** [comment]
Use 2.x branch of apktool - you'll have to build it from sources. You can also try to set SMALI_FILE_EXT = 'smali' and LINE_PREFIX = '' in common.py and use apktool 1.x, but I didn't try it by myself.

**Comment by ZsBT** [comment]
OK thanks I'll find the right solution.
