### ISSUE TITLE
Build Help

### ISSUE THREAD

**Issue by fatflyingpigs** [broo2s/ingress-apk-mod#13]
I'm an ammature dev that wanted to add to this mod, mainly because the current ingress app isn't at it's fullest potential. I'm having an issue building the app (yes, I'm aware it's "not that easy to build," but I've gotten pretty far and seem to be at a small road block).
I am running ubuntu 13, and I believe I have all the dependencies including python3, pyyaml, java, all PATH deps, and all necessary files in the lib folder. The extras jars were "just in case" it actually helped. Other than the lib folder and files within, no other files or folders have been added to the initial repo pull.
![capture](https://f.cloud.github.com/assets/2653682/792166/f0683aa2-eb72-11e2-8dbc-2be897a51e7b.PNG)

The following code is the exactly what I ran, as well as the following output. The first place I see the error is at, `grep: /home/jordan/ingress-apk-mod/app/smali/com/nianticproject/ingress/common: No such file or directory`

```
jordan@jordan-VirtualBox:~$ cd ingress-apk-mod/bin/
jordan@jordan-VirtualBox:~/ingress-apk-mod/bin$ python3 import_apk.py "/home/jordan/com.nianticproject.ingress-1.apk" 
Apktool v1.5.2 - a tool for reengineering Android apk files
Copyright 2010 Ryszard Wiśniewski <brut.alll@gmail.com>
with smali v1.4.1, and baksmali v1.4.1
Updated by @iBotPeaches <connor.tumbleson@gmail.com> 
Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

Usage: apktool [-q|--quiet OR -v|--verbose] COMMAND [...]

COMMANDs are:

    d[ecode] [OPTS] <file.apk> [<dir>]
        Decode <file.apk> to <dir>.

        OPTS:

        -s, --no-src
            Do not decode sources.
        -r, --no-res
            Do not decode resources.
        -d, --debug
            Decode in debug mode. Check project page for more info.
        -b, --no-debug-info
            Baksmali -- don't write out debug info (.local, .param, .line, etc.)
        -f, --force
            Force delete destination directory.
        -t <tag>, --frame-tag <tag>
            Try to use framework files tagged by <tag>.
        --frame-path <dir>
            Use the specified directory for framework files
        --keep-broken-res
            Use if there was an error and some resources were dropped, e.g.:
            "Invalid config flags detected. Dropping resources", but you
            want to decode them anyway, even with errors. You will have to
            fix them manually before building.

    b[uild] [OPTS] [<app_path>] [<out_file>]
        Build an apk from already decoded application located in <app_path>.

        It will automatically detect, whether files was changed and perform
        needed steps only.

        If you omit <app_path> then current directory will be used.
        If you omit <out_file> then <app_path>/dist/<name_of_original.apk>
        will be used.

        OPTS:

        -f, --force-all
            Skip changes detection and build all files.
        -d, --debug
            Build in debug mode. Check project page for more info.
        -a, --aapt
            Loads aapt from specified location.

    if|install-framework <framework.apk> [<tag>] --frame-path [<location>] 
        Install framework file to your system.

For additional info, see: http://code.google.com/p/android-apktool/
For smali/baksmali info, see: http://code.google.com/p/smali/
~/ingress-apk-mod/app ~/ingress-apk-mod/bin
Initialized empty Git repository in /home/jordan/ingress-apk-mod/app/.git/
[master (root-commit) d542134] Import.
 1 file changed, 6 insertions(+)
 create mode 100644 .gitignore
Counting objects: 3, done.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), done.
Total 3 (delta 0), reused 0 (delta 0)
~/ingress-apk-mod/bin
grep: /home/jordan/ingress-apk-mod/app/smali/com/nianticproject/ingress/common: No such file or directory
Traceback (most recent call last):
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 272, in <module>
    Analyzer().analyze(len(sys.argv) > 1 and sys.argv[1] == 'release')
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 22, in analyze
    self.auto_analyze()
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 86, in auto_analyze
    found, unknown_pkg = self.auto_identify_class(cls, max_unknown_pkg)
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 123, in auto_identify_class
    ret = find_class(q)
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 114, in find_class
    ret = set(getattr(self, 'find_class_' + q[0])(*([cls, (obf_pkg, unknown)] + q[3:])))
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 177, in find_class_by_string
    return self.find_classes_by_string(self.obj.expr(s, regex=True), pkg)
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 267, in find_classes_by_string
    out = subprocess.check_output(grep % (s.replace('"', r'\"'), smali_dir, '/'.join(pkg)), shell=True).decode()
  File "/usr/lib/python3.3/subprocess.py", line 586, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'grep -P -l -r "onEnterForeground" /home/jordan/ingress-apk-mod/app/smali/com/nianticproject/ingress/common' returned non-zero exit status 2
Traceback (most recent call last):
  File "import_apk.py", line 28, in <module>
    main(sys.argv[1])
  File "import_apk.py", line 24, in main
    ''' % (LINE_PREFIX, apk), shell=True, executable='/bin/bash')
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        rm -rf $MOD_HOME/app
        java -jar $MOD_HOME/lib/apktool.jar d -d -o $MOD_HOME/app --debug-line-prefix ';// ' "/home/jordan/com.nianticproject.ingress-1.apk"
        mkdir -p $MOD_HOME/app  # to not mess up everything if apktool fail
        cp $MOD_HOME/res/app.gitignore $MOD_HOME/app/.gitignore

        pushd $MOD_HOME/app
        git init
        git add -f .
        git commit -m "Import."
        git gc
        popd

        $MOD_HOME/bin/analyze.py
    ' returned non-zero exit status 1
```

If there are any ideas of how I might go about fixing it, that would be awesome!

**Comment by ghost** [comment]
hi,

i am far away to be an expert but : 

First you use the version 1.5.2 of apktool, you should compile and use v2 :

```
git clone https://github.com/iBotPeaches/Apktool.git -b wip-2.0
cd Apktool/
./gradlew build fatJar
```

The compiled jar is `./brut.apktool/apktool-cli/build/libs/apktool-cli-2.0.0-Beta4.jar` for me.

Also your lib file are not well named you should have something like this :

```
vmdeb7-mal:~# ls -l /ingress/ingress-apk-mod/lib/
total 37104
-rwxr-xr-x 1 root root 19090582 Jul 10 00:49 android.jar
-rwxr-xr-x 1 root root 11181597 Jul 10 00:49 apktool.jar
-rwxr-xr-x 1 root root   541043 Jul 10 00:49 baksmali.jar
-rwxr-xr-x 1 root root  1434724 Jul 10 00:49 gdx-backend-lwjgl.jar
-rwxr-xr-x 1 root root  1453129 Jul 10 00:49 gdx-backend-lwjgl-natives.jar
-rwxr-xr-x 1 root root  1060515 Jul 10 00:49 gdx.jar
-rwxr-xr-x 1 root root  1158615 Jul 10 00:49 gdx-natives.jar
-rwxr-xr-x 1 root root  2063723 Jul 10 00:49 gdx-tools.jar
```

and to finish my apk has to be named `ingress-<xyz>.apk` for me.

regards, maladeras

**Comment by broo2s** [comment]
Yes, @Maladeras is right, this is because you use apktool 1.x and it has broken "-d" switch. And as I said here: https://github.com/brutall/ingress-apk-mod/issues/1#issuecomment-20634569 - "You can also try to set SMALI_FILE_EXT = 'smali' and LINE_PREFIX = '' in common.py and use apktool 1.x, but I didn't try it by myself."

I know it may not be that easy even for developers and should be improved, but as you maybe know I got C&D for this project, so I will rather remove than iprove it.

**Comment by fatflyingpigs** [comment]
Thanks for the help guys. I followed the first segment of Maladeras' code, however, I revieved this error when running `./gradlew build fatJar`

```
jordan@jordan-VirtualBox:~/Apktool$ ./gradlew build fatJar
[ant:loadfile] /home/jordan/Apktool/.git/refs/heads/master doesn't exist
Building SNAPSHOT (no .git folder found)
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:licenseMain UP-TO-DATE
:licenseTest UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test
:check
:build
:brut.apktool:compileJava UP-TO-DATE
:brut.apktool:processResources UP-TO-DATE
:brut.apktool:classes UP-TO-DATE
[This goes on for a while, until]

brut.androlib.BuildAndDecodeTest > classMethod FAILED
    brut.androlib.AndrolibException at BuildAndDecodeTest.java:47
        Caused by: brut.androlib.AndrolibException at BuildAndDecodeTest.java:47
            Caused by: brut.common.BrutException at BuildAndDecodeTest.java:47
                Caused by: java.io.IOException at BuildAndDecodeTest.java:47
                    Caused by: java.io.IOException at BuildAndDecodeTest.java:47

1 test completed, 1 failed
:brut.apktool:apktool-lib:test FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:test'.
There were failing tests. See the report at: file:///home/jordan/Apktool/brut.apktool/apktool-lib/build/reports/tests/index.html

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

stacktrace gave
`* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':brut.apktool:apktool-lib:test'.` at a variety of locations.

1 of the 2 tests failed. I'm not sure as to what caused this.
![capture](https://f.cloud.github.com/assets/2653682/792884/c575f334-ebcc-11e2-82e1-3f614041dc64.PNG)

At any rate, the jar file was there (bad jar file or not, it was there), so I made the remaining changes and tried it again. It didn't work:

```
jordan@jordan-VirtualBox:~/ingress-apk-mod/bin$ sudo python3 import_apk.py "/home/jordan/ingress-1.apk" 
no main manifest attribute, in /home/jordan/ingress-apk-mod/lib/apktool.jar
~/ingress-apk-mod/app ~/ingress-apk-mod/bin
Initialized empty Git repository in /home/jordan/ingress-apk-mod/app/.git/
[master (root-commit) 9c50bbf] Import.
 1 file changed, 6 insertions(+)
 create mode 100644 .gitignore
Counting objects: 3, done.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), done.
Total 3 (delta 0), reused 0 (delta 0)
~/ingress-apk-mod/bin
grep: /home/jordan/ingress-apk-mod/app/smali/com/nianticproject/ingress/common: No such file or directory
Traceback (most recent call last):
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 272, in <module>
    Analyzer().analyze(len(sys.argv) > 1 and sys.argv[1] == 'release')
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 22, in analyze
    self.auto_analyze()
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 86, in auto_analyze
    found, unknown_pkg = self.auto_identify_class(cls, max_unknown_pkg)
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 123, in auto_identify_class
    ret = find_class(q)
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 114, in find_class
    ret = set(getattr(self, 'find_class_' + q[0])(*([cls, (obf_pkg, unknown)] + q[3:])))
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 177, in find_class_by_string
    return self.find_classes_by_string(self.obj.expr(s, regex=True), pkg)
  File "/home/jordan/ingress-apk-mod/bin/analyze.py", line 267, in find_classes_by_string
    out = subprocess.check_output(grep % (s.replace('"', r'\"'), smali_dir, '/'.join(pkg)), shell=True).decode()
  File "/usr/lib/python3.3/subprocess.py", line 586, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'grep -P -l -r "\"ScannerActivity\"" /home/jordan/ingress-apk-mod/app/smali/com/nianticproject/ingress/common' returned non-zero exit status 2
Traceback (most recent call last):
  File "import_apk.py", line 28, in <module>
    main(sys.argv[1])
  File "import_apk.py", line 24, in main
    ''' % (LINE_PREFIX, apk), shell=True, executable='/bin/bash')
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        rm -rf $MOD_HOME/app
        java -jar $MOD_HOME/lib/apktool.jar d -d -o $MOD_HOME/app --debug-line-prefix ';// ' "/home/jordan/ingress-1.apk"
        mkdir -p $MOD_HOME/app  # to not mess up everything if apktool fail
        cp $MOD_HOME/res/app.gitignore $MOD_HOME/app/.gitignore

        pushd $MOD_HOME/app
        git init
        git add -f .
        git commit -m "Import."
        git gc
        popd

        $MOD_HOME/bin/analyze.py
    ' returned non-zero exit status 1
```

The `no main manifest attribute, in /home/jordan/ingress-apk-mod/lib/apktool.jar` would seem to be the problem. Is this a problem with the package or am I missing some dependency when I gradlew?

@brutall When you say remove it than improve it, what are you referring to by "it"? This entire repo? or the apktool dependency?

**Comment by ZsBT** [comment]
@fatflyingpigs I think your apktool build is not fully functional. You can find a working version here: https://www.dropbox.com/s/0vz1oh53j754mge/deps-pack.tar
Regarding to phrase 'remove it' , I'm afraid it means the entire repo, as n.i.a. is hunting this mod by its copyright grounds.

**Comment by fatflyingpigs** [comment]
Thank you for the files, ZsBT. I coppied all the files, including the 

It looks like this should be my last error. I'm on the 3rd step `Run release.py to create two optimized apk files: regular and muted.` This error occurs regardless of running step 2.
The problem starts at `Exception in thread "main" brut.androlib.AndrolibException``

Reading down, there were only 2 files I could find that made sense of. `/home/jordan/apktool/framework/1.apk`, which consisted of a single file called `resources.arsc`, 6.1 MB.
The other file I recognized was the `AndroidManifest.xml`; it appeared to be complete/correct.

```
jordan@jordan-VirtualBox:~/ingress-apk-mod/bin$ python3 release.py 
~/ingress-apk-mod/app ~/ingress-apk-mod/bin
HEAD is now at cec4a9d Import.
~/ingress-apk-mod/bin
ProGuard, version 4.7
Reading program directory [/home/jordan/ingress-apk-mod/build/src]
Reading library directory [/home/jordan/ingress-apk-mod/build/ifc]
Reading library jar [/home/jordan/ingress-apk-mod/lib/android.jar]
Reading library jar [/home/jordan/ingress-apk-mod/lib/gdx.jar]
Preparing output directory [/home/jordan/ingress-apk-mod/build/proguard]
  Copying resources from program directory [/home/jordan/ingress-apk-mod/build/src]
I: Checking whether sources has changed...
I: Smaling...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_700615778631308435.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, 10302, --version-name, 1.30.2, -F, /tmp/APKTOOL3640161138740083811.tmp, -0, arsc, -I, /home/jordan/apktool/framework/1.apk, -S, /home/jordan/ingress-apk-mod/app/res, -M, /home/jordan/ingress-apk-mod/app/AndroidManifest.xml]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:431)
    at brut.androlib.Androlib.buildResources(Androlib.java:359)
    at brut.androlib.Androlib.build(Androlib.java:282)
    at brut.androlib.Androlib.build(Androlib.java:257)
    at brut.apktool.Main.cmdBuild(Main.java:229)
    at brut.apktool.Main.main(Main.java:88)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_700615778631308435.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, 10302, --version-name, 1.30.2, -F, /tmp/APKTOOL3640161138740083811.tmp, -0, arsc, -I, /home/jordan/apktool/framework/1.apk, -S, /home/jordan/ingress-apk-mod/app/res, -M, /home/jordan/ingress-apk-mod/app/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:483)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:412)
    ... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_700615778631308435.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, 10302, --version-name, 1.30.2, -F, /tmp/APKTOOL3640161138740083811.tmp, -0, arsc, -I, /home/jordan/apktool/framework/1.apk, -S, /home/jordan/ingress-apk-mod/app/res, -M, /home/jordan/ingress-apk-mod/app/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:93)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:477)
    ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_700615778631308435.tmp": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
    at java.lang.Runtime.exec(Runtime.java:615)
    at java.lang.Runtime.exec(Runtime.java:483)
    at brut.util.OS.exec(OS.java:84)
    ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
    ... 10 more
ls: cannot access /home/jordan/ingress-apk-mod/app/dist/ingress-*.apk: No such file or directory
jarsigner: unable to open jar file: release
Traceback (most recent call last):
  File "/home/jordan/ingress-apk-mod/bin/sign_apk.py", line 17, in <module>
    main(sys.argv[1], len(sys.argv) > 2 and sys.argv[2] == 'release')
  File "/home/jordan/ingress-apk-mod/bin/sign_apk.py", line 13, in main
    ''' % (p['store'], p['pass'], apk, p['alias']), shell=True)
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        jarsigner -sigalg MD5withRSA -digestalg SHA1 -keystore "$MOD_HOME/res/ingress-mod.keystore" -storepass "qwerty" release "ingress_mod"
    ' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/jordan/ingress-apk-mod/bin/build.py", line 60, in <module>
    main(len(sys.argv) > 1 and sys.argv[1] == 'release')
  File "/home/jordan/ingress-apk-mod/bin/build.py", line 34, in main
    ''' % (('release', '', 'release') if release else ('debug', ' -d', 'debug')), shell=True)
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        builddir="$MOD_HOME/build"

        rm -rf $builddir/ifc $builddir/src $builddir/proguard $builddir/dex.apk $builddir/smali $MOD_HOME/app/smali/broot $MOD_HOME/app/smali/a/*.smali
        mkdir -p $builddir/ifc $builddir/src

        javac -Xlint:-options -g:none -source 6 -target 6 -cp $MOD_HOME/lib/android.jar:$MOD_HOME/lib/gdx.jar -d $builddir/ifc `find -H $MOD_HOME/ifc -type f -iname "*.java"`
        javac -Xlint:-options -g -source 6 -target 6 -cp $builddir/ifc:$MOD_HOME/lib/android.jar:$MOD_HOME/lib/gdx.jar -d $builddir/src `find -H $MOD_HOME/src -type f -iname "*.java" -not -name BuildConfig.java` $MOD_HOME/build/BuildConfig.java

        proguard.sh @$MOD_HOME/res/release.pg

        dx --dex --output=$builddir/dex.apk $builddir/proguard
        java -jar $MOD_HOME/lib/baksmali.jar $builddir/dex.apk -o $builddir/smali

        cp -r $builddir/smali/* $MOD_HOME/app/smali/
        java -jar $MOD_HOME/lib/apktool.jar b $MOD_HOME/app
        $MOD_HOME/bin/sign_apk.py `ls $MOD_HOME/app/dist/ingress-*.apk` release
    ' returned non-zero exit status 1
/bin/bash: line 13: /home/jordan/adt-bundle-linux-x86_64-20130522/sdk/tools/zipalign: No such file or directory
~/ingress-apk-mod/app ~/ingress-apk-mod/bin
HEAD is now at cec4a9d Import.
Removing assets/common/data-hvga/
Removing assets/common/data-qvga/
Removing assets/packed/data-hvga/
Removing assets/packed/data-qvga/
Removing assets/portal_info/data-hvga/
Removing assets/portal_info/data-qvga/
Removing assets/upgrade/data-hvga/
Removing assets/upgrade/data-qvga/
Removing build/
Removing smali/A.smali
Removing smali/[all the other letters.smali too, fatflyingpigs]
~/ingress-apk-mod/bin
ProGuard, version 4.7
Reading program directory [/home/jordan/ingress-apk-mod/build/src]
Reading library directory [/home/jordan/ingress-apk-mod/build/ifc]
Reading library jar [/home/jordan/ingress-apk-mod/lib/android.jar]
Reading library jar [/home/jordan/ingress-apk-mod/lib/gdx.jar]
Preparing output directory [/home/jordan/ingress-apk-mod/build/proguard]
  Copying resources from program directory [/home/jordan/ingress-apk-mod/build/src]
I: Checking whether sources has changed...
I: Smaling...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3751516841807548881.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, 10302, --version-name, 1.30.2, -F, /tmp/APKTOOL9171082362251934392.tmp, -0, arsc, -I, /home/jordan/apktool/framework/1.apk, -S, /home/jordan/ingress-apk-mod/app/res, -M, /home/jordan/ingress-apk-mod/app/AndroidManifest.xml]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:431)
    at brut.androlib.Androlib.buildResources(Androlib.java:359)
    at brut.androlib.Androlib.build(Androlib.java:282)
    at brut.androlib.Androlib.build(Androlib.java:257)
    at brut.apktool.Main.cmdBuild(Main.java:229)
    at brut.apktool.Main.main(Main.java:88)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3751516841807548881.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, 10302, --version-name, 1.30.2, -F, /tmp/APKTOOL9171082362251934392.tmp, -0, arsc, -I, /home/jordan/apktool/framework/1.apk, -S, /home/jordan/ingress-apk-mod/app/res, -M, /home/jordan/ingress-apk-mod/app/AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:483)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:412)
    ... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3751516841807548881.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, 10302, --version-name, 1.30.2, -F, /tmp/APKTOOL9171082362251934392.tmp, -0, arsc, -I, /home/jordan/apktool/framework/1.apk, -S, /home/jordan/ingress-apk-mod/app/res, -M, /home/jordan/ingress-apk-mod/app/AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:93)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:477)
    ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_3751516841807548881.tmp": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
    at java.lang.Runtime.exec(Runtime.java:615)
    at java.lang.Runtime.exec(Runtime.java:483)
    at brut.util.OS.exec(OS.java:84)
    ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
    ... 10 more
ls: cannot access /home/jordan/ingress-apk-mod/app/dist/ingress-*.apk: No such file or directory
jarsigner: unable to open jar file: release
Traceback (most recent call last):
  File "/home/jordan/ingress-apk-mod/bin/sign_apk.py", line 17, in <module>
    main(sys.argv[1], len(sys.argv) > 2 and sys.argv[2] == 'release')
  File "/home/jordan/ingress-apk-mod/bin/sign_apk.py", line 13, in main
    ''' % (p['store'], p['pass'], apk, p['alias']), shell=True)
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        jarsigner -sigalg MD5withRSA -digestalg SHA1 -keystore "$MOD_HOME/res/ingress-mod.keystore" -storepass "qwerty" release "ingress_mod"
    ' returned non-zero exit status 1
Traceback (most recent call last):
  File "/home/jordan/ingress-apk-mod/bin/build.py", line 60, in <module>
    main(len(sys.argv) > 1 and sys.argv[1] == 'release')
  File "/home/jordan/ingress-apk-mod/bin/build.py", line 34, in main
    ''' % (('release', '', 'release') if release else ('debug', ' -d', 'debug')), shell=True)
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        builddir="$MOD_HOME/build"

        rm -rf $builddir/ifc $builddir/src $builddir/proguard $builddir/dex.apk $builddir/smali $MOD_HOME/app/smali/broot $MOD_HOME/app/smali/a/*.smali
        mkdir -p $builddir/ifc $builddir/src

        javac -Xlint:-options -g:none -source 6 -target 6 -cp $MOD_HOME/lib/android.jar:$MOD_HOME/lib/gdx.jar -d $builddir/ifc `find -H $MOD_HOME/ifc -type f -iname "*.java"`
        javac -Xlint:-options -g -source 6 -target 6 -cp $builddir/ifc:$MOD_HOME/lib/android.jar:$MOD_HOME/lib/gdx.jar -d $builddir/src `find -H $MOD_HOME/src -type f -iname "*.java" -not -name BuildConfig.java` $MOD_HOME/build/BuildConfig.java

        proguard.sh @$MOD_HOME/res/release.pg

        dx --dex --output=$builddir/dex.apk $builddir/proguard
        java -jar $MOD_HOME/lib/baksmali.jar $builddir/dex.apk -o $builddir/smali

        cp -r $builddir/smali/* $MOD_HOME/app/smali/
        java -jar $MOD_HOME/lib/apktool.jar b $MOD_HOME/app
        $MOD_HOME/bin/sign_apk.py `ls $MOD_HOME/app/dist/ingress-*.apk` release
    ' returned non-zero exit status 1
/bin/bash: line 23: /home/jordan/adt-bundle-linux-x86_64-20130522/sdk/tools/zipalign: No such file or directory
Traceback (most recent call last):
  File "release.py", line 37, in <module>
    main()
  File "release.py", line 33, in main
    ''' % config['version'], shell=True, executable='/bin/bash')
  File "/usr/lib/python3.3/subprocess.py", line 544, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '
        version=1.0.0

        f=`grep apkFileName $MOD_HOME/app/apktool.yml`
        f=${f:13:${#f}-17}

        $MOD_HOME/bin/clean_app.py
        $MOD_HOME/bin/analyze.py release

        $MOD_HOME/bin/main.py
        $MOD_HOME/bin/copy_assets.py
        $MOD_HOME/bin/build.py release
        rm -f $MOD_HOME/$f-broot-$version.apk
        zipalign 4 $MOD_HOME/app/dist/$f.apk $MOD_HOME/$f-broot-$version.apk


        $MOD_HOME/bin/clean_app.py

        $MOD_HOME/bin/main.py
        $MOD_HOME/bin/copy_assets.py
        $MOD_HOME/bin/mute.py
        $MOD_HOME/bin/build.py release
        rm -f $MOD_HOME/$f-broot-$version-mute.apk
        zipalign 4 $MOD_HOME/app/dist/$f.apk $MOD_HOME/$f-broot-$version-mute.apk
    ' returned non-zero exit status 127

```

Thanks in advance!

**Comment by ghost** [comment]
hi,

the error is here 

```
ls: cannot access /home/jordan/ingress-apk-mod/app/dist/ingress-*.apk: No such file or directory
```

As i said in my previous comment, your apk should match `ingress-*.apk` 

For example my apk is named ingress-1.30.2.apk.

regards, maladeras

**Comment by fatflyingpigs** [comment]
@Maladeras: I actually did change that. My apk is named ingress-1.apk; it is a version 1.30.2 ingress apk. I also just verified that the apk is undamaged.
`jordan@jordan-VirtualBox:~/ingress-apk-mod/bin$ python3 import_apk.py "/home/jordan/ingress-1.apk"`
It would appear that after the 1st step, no folder called `dist` is made in `/home/jordan/ingress-apk-mod/app/`.
The end of step 1 is:

```
create mode 100644 unknown/jsr330_inject/Jsr330_inject.gwt.xml
create mode 100644 unknown/jsr330_inject/v0_r67/V0_r67.gwt.xml
Counting objects: 6314, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6183/6183), done.
Writing objects: 100% (6314/6314), done.
Total 6314 (delta 4232), reused 0 (delta 0)
~/ingress-apk-mod/bin
jordan@jordan-VirtualBox:~/ingress-apk-mod/bin$ 
jordan@jordan-VirtualBox:~/ingress-apk-mod/bin$ python3 release.py 
```

At which point the error in my previous comment will happen.

**Comment by ghost** [comment]
@fatflyingpigs i don't understand what is going wrong, sorry.

Have you tried to delete all file ( save the lib directory before :) ) and clone this git again, in order to try with a clean workspace  ?

**Comment by fatflyingpigs** [comment]
@Maladeras I just tried a fresh pull - it didn't work. Is the `dist` folder and the `/dist/ingress-*.apk` supposed to be made after step 1? This way I will know in which step my problem lies.

**Comment by ghost** [comment]
@fatflyingpigs i don't remember, sorry. I can't check it right now. Can you paste ( with Gists or in attachment ) all the log of you import and release ?

**Comment by fatflyingpigs** [comment]
@Maladeras Thanks for your help and time. Here are the out and err files for both the import and release.

import_apk.out - https://gist.github.com/fatflyingpigs/5993194
import_apk.err - https://gist.github.com/fatflyingpigs/5993199

release.out - https://gist.github.com/fatflyingpigs/5993201
release.err - https://gist.github.com/fatflyingpigs/5993202

Terminal code:
![capture](https://f.cloud.github.com/assets/2653682/793792/f4e84dfe-ec3c-11e2-97a4-fc4122b07bdf.PNG)

**Comment by ghost** [comment]
@fatflyingpigs, sory but i still don't understand... have you check if aapt is working well ? ( juste type aapt in shell :) )

**Comment by fatflyingpigs** [comment]
Thanks @Maladeras! Typing `aapt` gave a `No such file or directory`. I google around and figured it out. I put the app on my phone and it is fully functional.

According to http://bit.ly/13ahmwc,
`This is a 64-bit issue, aapt is apparently expecting 32-bit libraries and you have 64-bit libs.`
`apt-get install ia32-libs`

And according to http://bit.ly/17IVRWy,
`It appears that the latest update to the r22 SDK release moved aapt and the lib jar from the platform-tools to the build-tools directory.`

```
ln -s ../build-tools/17.0.0/aapt aapt
ln -s ../build-tools/17.0.0/lib lib
```

Note: "17.0.0" was "android-4.2.2" for me. I did both, so I'm not sure which if only 1 was necessary.

A couple tips to anyone that's having the same trouble building: `dx, adb, zipalign, jarsigner in PATH` `dx, adb, and zipalign` can be found somewhere within the Android SDK. `jarsigner` can be found in the same directory as the `javac` PATH. Throw your path environment variables into `.bashrc` and restart after for fewer headaches.
A couple dependencies I had to install on a fresh Ubuntu install: `python3` (as opposed to native python2.7), python3 `pyyaml`, python3 `PIL`. Install help can be found with google.

**Comment by ZsBT** [comment]
@fatflyingpigs  Yep signing apk neither worked for me the first time, but i sign them
manually with my keys. Actually i created a new github branch that supports
those environments where no PIL for python3 is available.
2013.07.14. 3:18, "Maladeras ISCARIOTE" notifications@github.com ezt írta:
